name: CI

on:
  push:
    branches:
      - main
      - 'v*'
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-test
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml

  tests:
    runs-on: ${{ matrix.os }}
    needs: [build]

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.10, 3.11, 3.12, 3.13, 3.14]
        test-target: []
        include:
          - os: ubuntu-latest
            python-version: 3.14
            test-target: cov
          - os: ubuntu-latest
            python-version: 3.14
            test-target: dev

          - os: ubuntu-latest
            python-version: 3.10
            test-target: numpy125
          - os: ubuntu-latest
            python-version: 3.10
            test-target: numpy122


    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: actions/download-artifact@v7
        with:
          pattern: dist-*
          path: dist
          merge-multiple: true

      - name: List files
        run: |
          echo CWD is $(pwd)
          find dist -name '*.whl'

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: '${{ matrix.python-version }}'

      - name: Install Just
        uses: extractions/setup-just@v3

      - name: Test ${{ matrix.test-target }}
        run: |
          find . -name '*.whl'
          just --set BUILD_DISABLE 1 test ${{ matrix.test-target }}

    #secrets:
    #  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
